-- CreateTable
CREATE TABLE "imc" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "value" REAL NOT NULL,
    "dateValue" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
